services:
  db:
    image: postgres:15
    container_name: tzylo-db
    restart: always
    environment:
      POSTGRES_USER: tzylo
      POSTGRES_PASSWORD: tzylo
      POSTGRES_DB: auth
    volumes:
      - tzylo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tzylo"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth:
    image: tzylo-auth-ce:latest
    container_name: tzylo-auth
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://tzylo:tzylo@db:5432/auth"
      JWT_SECRET: "supersecret"
      NODE_ENV: "production"
      PORT: "7200"
    ports:
      - "7200:7200"

volumes:
  tzylo-db-data:
